1. Write a Python program to calculate the area of a rectangle given its length and width.

In [ ]:
length=float(input("Enter length: "))
width=float(input("Enter width: "))
area=length*width
print("Area of a Rectangle is: %.2f"%area)

Enter length: 3.4
Enter width: 2.8
Area of a Rectangle is: 9.52


2. Write a program to convert miles to kilometers


In [ ]:
miles = float(input("Enter value in miles: "))
conversion_factor=1.60934
kilometers=miles*conversion_factor
print(f"{miles} miles is equal to {kilometers} kilometers")

Enter value in miles: 10
10.0 miles is equal to 16.0934 kilometers


3. Write a function to check if a given string is a palindrome.

In [ ]:
string = input ("Enter string: ")
if string==string[::-1]:
  print("The string is a palindrome." )
else:
  print("The string is not a palindrome.")


Enter string: amma
The string is a palindrome.


4. Write a Python program to find the second largest element in a list.


In [ ]:
list1 = [30, 24, 43, 2, 25, 54, 64, 75, 99]
list2 = list(set(list1))
list2.sort()
print("Second largest element is:", list2[-2])

Second largest element is: 75


5. Explain what indentation means in Python.

In Python, indentation refers to the use of whitespace (usually spaces or tabs) at the beginning of a line to indicate the block structure of the code.

6. Write a program to perform set difference operation.


In [2]:
set1 = {1, 2, 3, 14, 5}
set2 = {14, 5, 6, 7, 9}
print("Set Difference:", set1 - set2)

Set Difference: {1, 2, 3}


7. Write a Python program to print numbers from 1 to 10 using a while loop.

In [3]:
number = 1
while number <= 10:
    print(number)
    number += 1

1
2
3
4
5
6
7
8
9
10


8. Write a program to calculate the factorial of a number using a while loop.

In [4]:
def factorial(n):
    fact = 1
    while n > 0:
        fact *= n
        n -= 1
    return fact


num = int(input("Enter a number: "))
if num < 0:
    print("Factorial is not defined for negative numbers.")
else:
    print("Factorial of", num, "is", factorial(num))

Enter a number: 3
Factorial of 3 is 6


9. Write a Python program to check if a number is positive, negative, or zero using if-elif-else
statements.

In [6]:
number= int(input("Enter a number: "))
if number>0:
  print("The number is positive.")
elif number<0:
  print("The number is negative.")
else:
  print("The number is zero.")

Enter a number: -36
The number is negative.


10. Write a program to determine the largest among three numbers using conditional
statements.

In [8]:
num1 =float(input("Enter the first number: "))
num2 =float(input("Enter the second number: "))
num3 =float(input("Enter the third number: "))
if num1>num2 and num1>num3:
  largest=num1
elif num2>num1 and num2>num3:
  largest=num2
else:
  largest=num3
print("The largest number among", num1, ",", num2, ", and", num3, "is", largest)

Enter the first number: 3.4
Enter the second number: 8.2
Enter the third number: 1.4
The largest number among 3.4 , 8.2 , and 1.4 is 8.2


11. Write a Python program to create a numpy array filled with ones of given shape

In [9]:
import numpy as np

def create_ones_array(shape):
    ones_array = np.ones(shape)
    return ones_array

rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))


ones_array = create_ones_array((rows, cols))


print("NumPy array filled with ones of shape", ones_array.shape, ":\n", ones_array)

Enter the number of rows: 3
Enter the number of columns: 5
NumPy array filled with ones of shape (3, 5) :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


12. Write a program to create a 2D numpy array initialized with random integers.

In [13]:
import numpy as np

def random_array(rows, cols, low, high):
    array = np.random.randint(low, high, size=(rows, cols))
    return array

rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))
low = int(input("Enter the lower bound of the range: "))
high = int(input("Enter the upper bound of the range: "))

random_array = random_array(rows, cols, low, high)
print("2D NumPy array initialized with random integers:\n", random_array)

Enter the number of rows: 5
Enter the number of columns: 6
Enter the lower bound of the range: 2
Enter the upper bound of the range: 8
2D NumPy array initialized with random integers:
 [[5 7 5 2 6 2]
 [4 3 5 2 7 5]
 [5 6 5 2 6 2]
 [4 2 6 6 3 3]
 [2 5 5 3 7 7]]


13. Write a Python program to generate an array of evenly spaced numbers over a specified
range using linspace.

In [14]:
import numpy as np

start = float(input("Enter the start of the range: "))
stop = float(input("Enter the end of the range: "))
num = int(input("Enter the number of evenly spaced numbers: "))

evenly_spaced_array = np.linspace(start, stop, num)

print("Array of evenly spaced numbers over the range [{}, {}]:\n{}".format(start, stop, evenly_spaced_array))

Enter the start of the range: 2
Enter the end of the range: 3
Enter the number of evenly spaced numbers: 5
Array of evenly spaced numbers over the range [2.0, 3.0]:
[2.   2.25 2.5  2.75 3.  ]


14. Write a program to generate an array of 10 equally spaced values between 1 and 100 using
linspace.

In [15]:
import numpy as np

equally_spaced_array = np.linspace(1, 100, 10)

print("Array of 10 equally spaced values between 1 and 100:\n", equally_spaced_array)

Array of 10 equally spaced values between 1 and 100:
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


15. Write a Python program to create an array containing even numbers from 2 to 20 using
arange.

In [16]:
import numpy as np

even_numbers_array = np.arange(2, 21, 2)

print("Array of even numbers from 2 to 20:\n", even_numbers_array)

Array of even numbers from 2 to 20:
 [ 2  4  6  8 10 12 14 16 18 20]


16. Write a program to create an array containing numbers from 1 to 10 with a step size of 0.5
using arange.

In [17]:
import numpy as np

array_with_step = np.arange(1, 10.5, 0.5)

print("Array containing numbers from 1 to 10 with a step size of 0.5:\n", array_with_step)


Array containing numbers from 1 to 10 with a step size of 0.5:
 [ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]
